version: '3.8'

services:
  # Neon Local proxy for development
  neon-local:
    image: neondatabase/neon_local:latest
    container_name: acquisitions-neon-local
    ports:
      - "5432:5432"
    env_file:
      - .env.development
    
    volumes:
      # Optional: Persist branch per Git branch
      - ./.neon_local/:/tmp/.neon_local
      - ./.git/HEAD:/tmp/.git/HEAD:ro,consistent
    networks:
      - acquisitions-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h localhost -p 5432 -U neon"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # Application service
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: acquisitions-app-dev
    ports:
      - "3000:3000"
    env_file:
      - .env.development
    volumes:
      # Mount source code for hot reloading
      - ./src:/app/src:cached
      - ./package.json:/app/package.json:cached
      - ./package-lock.json:/app/package-lock.json:cached
      # Exclude node_modules from host
      - /app/node_modules
    depends_on:
      neon-local:
        condition: service_healthy
    networks:
      - acquisitions-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

networks:
  acquisitions-network:
    driver: bridge

volumes:
  neon_local_data: